### PR TITLE
Custom Widget Title

### PR DESCRIPTION
**Pull request by grayghostvisuals**
Thought it would be cool to give this doo hickey the ability to have a custom title. Provides a fallback of "Dribbbles" if no title is specified. 

Sweet Plugin Dude!
:)

### CODE REVIEW

**Comment by davatron5000** [comment]
@grayghostvisuals, this worked in your implementation, yah? I'm clearing out PRs today and this one looks approvable.

**Comment by grayghostvisuals** [comment]
Yup last time I used it, although I no longer have the repo forked on my end. This was aaaages ago.

**Comment by davatron5000** [comment]
Congrats! You win! Not even gonna think twice about it unless someone barks.

**Comment by grayghostvisuals** [comment]
:thumbsup:

**Pull request merged**
